//
//  EventSource.swift
//  Special Event
//
//  Created by zzy on 2023/5/27.
//  Copyright © 2023 Personal usage. All rights reserved.
//

import Foundation
import SwiftUI

class EventSource: ObservableObject{
    @Published var showDetail = false
    @Published var selectedIndex = 0
    
    let appleEventList = [
        AppleEvent(
            titleColorSet: [.blue, .white, .blue, .white, .yellow],
            time: "September 7, 2022",
            title: "Far out.",
            detail: "Introducing an all-new iPhone lineup, rebuilt AirPods Pro, three new Apple Watch models, and an exciting update to Apple Fitness+.",
            thumbnail: "apple_event_22_9_7",
            modelName: "apple_event_22_9_7",
            modelExtension: "reality",
            sectionTitle: ["New product"],
            bigAttachmentIndex: [0, 5],
            bigAttachmentList: ["iPhone14Pro", "iPhone14", "AppleWatchS8", "AppleWatchUltra", "AirPodsPro2"],
            bigAttachmentTitle: ["iPhone 14 Pro", "iPhone 14", "Apple Watch S8", "Apple Watch Ultra", "AirPods Pro 2"]
        ),
        AppleEvent(
            titleColorSet: [.blue, .purple, .pink, .red, .orange, .yellow],
            time: "March 8, 2022",
            title: "Peek perfomance.",
            detail: "Introducing the all-new Mac Studio and Studio Display, new iPad Air, new iPhone SE, and iPhone 13 and iPhone 13 Pro in two new shades of green.",
            thumbnail: "apple_event_22_3_8",
            modelName: "apple_event_22_3_8",
            modelExtension: "reality",
            sectionTitle: ["New product"],
            bigAttachmentIndex: [0, 4],
            bigAttachmentList: ["macStudio&Display", "iPhone13Green", "iPhoneSE3", "iPadAirM1"],
            bigAttachmentTitle: ["Mac Studio and Studio Display", "iPhone 13 (Green)", "iPhone se3", "iPad Air (M1 chip)"]
        ),
        AppleEvent(
            titleColorSet: [.white, Color(red: 114/255, green: 154/255, blue: 248/255)],
            time: "October 18, 2021",
            title: "Unleashed.",
            detail: "Introducing the new MacBook Pro with M1 Pro or M1 Max, all-new AirPods, and HomePod mini in five bold colors.",
            thumbnail: "apple_event_21_10_18",
            modelName: "apple_event_21_10_18",
            modelExtension: "reality",
            sectionTitle: ["New product"],
            bigAttachmentIndex: [0, 3],
            bigAttachmentList: ["macBookPro14&16", "HomePodMini", "AirPods3"],
            bigAttachmentTitle: ["MacBook Pro 14 & 16 (M1 Pro and M1 Max chip)", "HomePod mini", "AirPods 3"]
        ),
        AppleEvent(
            titleColorSet: [Color(red: 29/255, green: 53/255, blue: 86/255), Color(red: 244/255, green: 187/255, blue: 204/255)],
            tcStart: .top,
            tcEnd: .bottom,
            time: "September 14, 2021",
            title: "California streaming.",
            detail: "Introducing iPhone 13 Pro, iPhone 13, Apple Watch Series 7, and the new iPad mini and iPad.",
            thumbnail: "apple_event_21_9_14",
            modelName: "apple_event_21_9_14",
            modelExtension: "reality",
            sectionTitle: ["New product"],
            bigAttachmentIndex: [0, 5],
            bigAttachmentList: ["iPhone13", "iPhone13Pro", "AppleWatchS7", "iPadmini", "iPad"],
            bigAttachmentTitle: ["iPhone 13", "iPhone 13 Pro", "Apple Watch S7", "iPad mini", "iPad"]
        ),
        AppleEvent(
            mainColor: .black,
            backgroundColor: [Color(red: 245/255, green: 245/255, blue: 247/255)],
            titleColorSet: [
                Color(red: 55/255, green: 126/255, blue: 147/255),
                Color(red: 181/255, green: 211/255, blue: 107/255),
                Color(red: 247/255, green: 207/255, blue: 70/255),
                Color(red: 240/255, green: 152/255, blue: 102/255),
                Color(red: 218/255, green: 84/255, blue: 69/255),
                Color(red: 232/255, green: 144/255, blue: 163/255),
                Color(red: 148/255, green: 98/255, blue: 183/255),
                Color(red: 65/255, green: 100/255, blue: 188/255),
                Color(red: 129/255, green: 177/255, blue: 221/255), ],
            time: "April 20, 2021",
            title: "Spring Loaded",
            detail: "Introducing the new iMac, iPad Pro, iPhone 12 in purple, AirTag, and Apple TV 4K.",
            thumbnail: "apple_event_21_4_20",
            modelName: "apple_event_21_4_20",
            modelExtension: "usdz",
            sectionTitle: ["New product"],
            bigAttachmentIndex: [0, 5],
            bigAttachmentList: ["iPhone12Purple", "iMacM1", "iPadPro2021", "AirTag", "AppleTV4K"],
            bigAttachmentTitle: ["iPhone 12 Purple", "iMac with M1", "iPad Pro with M1", "AirTag", "Apple TV 4K"]
        ),
        AppleEvent(
            titleColorSet: [.purple, .pink, .orange, .yellow, Color(red: 196/255, green: 197/255, blue: 200/255), .blue],
            time: "November 10, 2020",
            title: "One more thing.",
            detail: "Introducing the new MacBook Air, 13‑inch MacBook Pro, and Mac mini, all with the Apple M1 chip.",
            thumbnail: "apple_event_20_11_10",
            modelName: "apple_event_20_11_10",
            modelExtension: "usdz",
            sectionTitle: ["New product"],
            bigAttachmentIndex: [0, 3],
            bigAttachmentList: ["MacbookAirM1", "MacbookProM1", "Macmini"],
            bigAttachmentTitle: ["Macbook Air with M1", "Macbook Pro with M1", "Mac mini with M1"]
        ),
        AppleEvent(
            time: "October 13, 2020",
            title: "Hi, Speed.",
            detail: "Introducing iPhone 12 and iPhone 12 Pro with 5G, MagSafe accessories, and HomePod mini.",
            thumbnail: "apple_event_20_10_13",
            modelName: "apple_event_20_10_13",
            modelExtension: "usdz",
            sectionTitle: ["New product"],
            bigAttachmentIndex: [0, 3],
            bigAttachmentList: ["HomePodMini2", "iPhone12", "iPhone12Pro"],
            bigAttachmentTitle: ["HomePod mini", "iPhone 12", "iPhone 12 Pro"]
        ),
        AppleEvent(
            mainColor: .black,
            backgroundColor: [.white],
            titleColorSet: [Color(red: 25/255, green: 59/255, blue: 134/255),Color(red: 192/255, green: 224/255, blue: 247/255)],
            time: "September 15, 2020",
            title: "Time files.",
            detail: "Introducing Apple Watch Series 6, Apple Watch SE, Apple Fitness+, the new iPad Air and iPad, and Apple One — the all-new Apple services bundle.",
            thumbnail: "apple_event_20_9_15",
            modelName: "apple_event_20_9_15",
            modelExtension: "usdz",
            sectionTitle: ["New product"],
            bigAttachmentIndex: [0, 3],
            bigAttachmentList: ["AppleWatchS6", "AppleWatchSE", "iPadAir4th"],
            bigAttachmentTitle: ["Apple Watch S6", "Apple Watch SE", "iPad Air 4th"]
        ),
        AppleEvent(
            mainColor: .black,
            backgroundColor: [.white],
            titleColorSet: [.green.opacity(0.5), .blue.opacity(0.5), .yellow.opacity(0.5), .red.opacity(0.5), .purple.opacity(0.5)],
            time: "September 10, 2019",
            title: "By innovation only.",
            detail: "Announcing the new iPhone 11 Pro, iPhone 11, Apple Watch Series 5, and iPad.",
            thumbnail: "apple_event_19_9_10",
            sectionTitle: ["New product"],
            bigAttachmentIndex: [0, 3],
            bigAttachmentList: ["iPhone11", "iPhone11Pro", "AppleWatchS5"],
            bigAttachmentTitle: ["iPhone 11", "iPhone11 Pro/Pro Max", "Apple Watch S5"]
        ),
        AppleEvent(
            time: "March 25, 2019",
            title: "It's show time.",
            detail: "Announcing the new Apple TV+, Apple News+, Apple Arcade, and Apple Card.",
            thumbnail: "apple_event_19_3_25",
            sectionTitle: ["New services"],
            bigAttachmentIndex: [0, 4],
            bigAttachmentList: ["AppleTV+", "AppleNews+", "AppleArcade", "AppleCard"],
            bigAttachmentTitle: ["Apple TV+", "Apple News+", "Apple Arcade", "Apple Card"]
        ),
        AppleEvent(
            mainColor: .black,
            backgroundColor: [.white],
            titleColorSet: [.black],
            time: "October 30, 2018",
            title: "There's more in the making.",
            detail: "Announcing the new iPad Pro, MacBook Air, and Mac mini.",
            thumbnail: "apple_event_18_10_30",
            sectionTitle: ["New services"],
            bigAttachmentIndex: [0, 3],
            bigAttachmentList: ["iPadPro3rd", "Macmini2018", "MacbookAir2018"],
            bigAttachmentTitle: ["iPad Pro 3rd generation", "Mac mini", "Macbook Air"]
        ),
        AppleEvent(
            time: "September 12, 2018",
            title: "Gather round.",
            detail: "Announcing the new iPhone XS, iPhone XS Max, iPhone XR, and Apple Watch Series 4.",
            thumbnail: "apple_event_18_9_12"),
        AppleEvent(
            mainColor: .black,
            backgroundColor: [.white],
            titleColorSet: [.black],
            time: "March 27, 2018",
            title: "Let’s take a field trip.",
            detail: "Announcing the new iPad, which now supports Apple Pencil, and how teachers everywhere are using it to ignite creativity in their students.",
            thumbnail: "apple_event_18_3_27"),
        AppleEvent(
            time: "September 12, 2017",
            title: "Let’s meet at our place.",
            detail: "Announcements included a new generation of iPhone, Apple Watch with cellular connectivity, Apple TV 4K, and much more.",
            thumbnail: "apple_event_17_9_12"),
        AppleEvent(
            time: "October 27, 2016",
            title: "hello again",
            detail: "Take a look at our latest announcements, including the all-new MacBook Pro and the TV App for Apple TV.",
            thumbnail: "apple_event_16_10_27"),
        AppleEvent(
            time: "September 7, 2016",
            title: "See you on the 7th.",
            detail: "Watch the live event and check out the iPhone 7 and 7 Plus, the Apple Watch Series 2, and the wireless AirPods.",
            thumbnail: "apple_event_16_9_7"),
        AppleEvent(
            mainColor: .black,
            backgroundColor: [.white],
            titleColorSet: [.black],
            time: "March 21, 2016",
            title: "Let us loop you in.",
            detail: "Check out our live event and watch the introduction of the stunning 9.7-inch iPad Pro, beautiful new bands for Apple Watch, and iPhone SE — the most powerful 4‑inch phone ever.",
            thumbnail: "apple_event_16_3_21"),
        AppleEvent(
            mainColor: .black,
            backgroundColor: [.white],
            time: "September 9, 2015",
            title: "\"Hey Siri, give us a hint.\"",
            detail: "Check out iPhone 6s and iPhone 6s Plus, learn about the powerful iPad Pro, take a look at the new features and bands for Apple Watch, and see the premiere of the all-new Apple TV.",
            thumbnail: "apple_event_15_9_9"),
        AppleEvent(
            titleColorSet: [.black],
            time: "March 9, 2015",
            title: "Spring forward.",
            detail: "Get an in-depth look at Apple Watch, witness the unveiling of the new MacBook, and learn about the innovations in ResearchKit.",
            thumbnail: "apple_event_15_3_9"),
        
        AppleEvent(
            mainColor: .black,
            backgroundColor: [.white],
            titleColorSet: [.black],
            time: "October 16, 2014",
            title: "It's been way too long.",
            detail: "Get a first look at iMac with Retina 5K display and iPad Air 2, and learn about the release of OS X Yosemite.",
            thumbnail: "apple_event_14_10_16"),
        
        AppleEvent(
            mainColor: .black,
            backgroundColor: [.white],
            titleColorSet: [.black],
            time: "September 9, 2014",
            title: "Wish we could say more.",
            detail: "From the launch of Apple Watch to the arrival of iPhone 6 to a live performance from U2, this is an event not to be missed.",
            thumbnail: "apple_event_14_9_9"),
        // WWDC
        AppleEvent(
            time: "June 6, 2023",
            title: "Code new worlds.",
            detail: "Announcing Apple's biggest updates ever to iOS, iPadOS, watchOS — and what's more? Let's find out.",
            thumbnail: "wwdc23_6_6",
            modelName: "apple_event_23_6_6",
            modelExtension: "usdz"
        ),
        AppleEvent(
            time: "June 6, 2022",
            title: "Code one, code all.",
            detail: "Announcing Apple's biggest updates ever to iOS 16, iPadOS 16, watchOS 9 and macOS Ventura. Also introduced the new MacBook Air and 13-inch MacBook Pro with M2 chip.",
            thumbnail: "wwdc22_6_6",
            modelName: "apple_event_en_",
            modelExtension: "usdz",
            sectionTitle: ["New product"],
            bigAttachmentIndex: [0, 2],
            bigAttachmentList: ["macbookAirM2", "macbookPro13M2"],
            bigAttachmentTitle: ["Macbook Air with M2 chip", "Macbook Pro 13-inch with M2"],
            smallSectionTitle: ["New OS"],
            smallAttachmentIndex: [0, 5],
            smallAttachmentList: ["iOS16", "iPadOS16", "macOSVentura", "watchOS9", "tvOS"],
            smallAttachmentTitle: ["iOS 16", "iPadOS 16", "macOS Ventura", "watchOS 9", "tvOS 16"]
        ),
        AppleEvent(
            time: "June 6, 2021",
            title: "Glow and behold.",
            detail: "Announcing Apple's biggest updates ever to iOS, iPadOS, watchOS — and the entirely reimagined macOS Big Sur.",
            thumbnail: "wwdc21_6_6",
            sectionTitle: ["No new product release"],
            smallSectionTitle: ["New OS"],
            smallAttachmentIndex: [0, 5],
            smallAttachmentList: ["iOS15", "iPadOS15", "macOSMonterey", "watchOS8", "tvOS"],
            smallAttachmentTitle: ["iOS 15", "iPadOS 15", "macOS Monterey", "watchOS 8", "tvOS 15"]
        ),
        AppleEvent(
            time: "June 22, 2020",
            title: "Full stream ahead.",
            detail: "Announcing Apple's biggest updates ever to iOS, iPadOS, watchOS — and the entirely reimagined macOS Big Sur.",
            thumbnail: "wwdc20_6_22",
            sectionTitle: ["No new product release"],
            smallSectionTitle: ["New OS"],
            smallAttachmentIndex: [0, 5],
            smallAttachmentList: ["iOS14", "iPadOS14", "macOSBigSur", "watchOS", "tvOS"],
            smallAttachmentTitle: ["iOS 14", "iPadOS 14", "macOS BigSur", "watchOS 7", "tvOS 14"]
        ),
        AppleEvent(
            backgroundColor: [Color(red: 20/255, green: 26/255, blue: 45/255)],
            time: "June 3, 2019",
            title: "Write code. Blow minds.",
            detail: "Announcing upgraded operating systems for iPhone (iOS 14), Apple watch (watchOS 7) and Mac (macOS Catalina) - and a brand new one for iPad, iPadOS. And introducing the new Mac Pro and Pro Display XDR.",
            thumbnail: "wwdc19_6_3",
            sectionTitle: ["No new product release"],
            smallSectionTitle: ["New OS"],
            smallAttachmentIndex: [0, 5],
            smallAttachmentList: ["iOS13", "iPadOS13", "macOSCatalina", "watchOS", "tvOS"],
            smallAttachmentTitle: ["iOS 13", "iPadOS 13", "macOS Catalina", "watchOS 6", "tvOS 13"]
        ),
        AppleEvent(
            mainColor: .black,
            backgroundColor: [.white],
            titleColorSet: [.black],
            time: "June 4, 2018",
            title: "WWDC 2018",
            detail: "Announcing upgraded operating systems for iPhone and iPad, Mac, Apple Watch, and Apple TV.",
            thumbnail: "wwdc18_6_4",
            sectionTitle: ["No new product release"],
            smallSectionTitle: ["New OS"],
            smallAttachmentIndex: [0, 4],
            smallAttachmentList: ["iOS12", "macOSMojaveDark", "watchOS", "tvOS"],
            smallAttachmentTitle: ["iOS 12", "macOS Mojave", "watchOS 5", "tvOS 12"]
        ),
        AppleEvent(
            mainColor: .black,
            backgroundColor: [Color(red: 211/255, green: 211/255, blue: 211/255)],
            titleColorSet: [.black],
            time: "June 10, 2017",
            title: "WWDC 2017.",
            detail: "Check out the full event with announcements including a new size for iPad Pro, performance boosts across the Mac family, and a breakthrough speaker with HomePod.",
            thumbnail: "wwdc17_6_10",
            sectionTitle: ["New product"],
            bigAttachmentIndex: [0, 4],
            bigAttachmentList: ["iMac5K", "iMacPro", "iPadPro10.5", "HomePod"],
            bigAttachmentTitle: ["iMac 5K 27-inch", "iMac Pro 27-inch", "iPad Pro 10.5-inch", "HomePod"],
            smallSectionTitle: ["New OS"],
            smallAttachmentIndex: [0, 4],
            smallAttachmentList: ["iOS11", "macOSHighSierra", "watchOS", "tvOS"],
            smallAttachmentTitle: ["iOS 11", "macOS High Sierra", "watchOS 4", "tvOS 11"]
        ),
        AppleEvent(
            backgroundColor: [Color(red: 40/255, green: 42/255, blue: 53/255)],
            titleColorSet: [.white],
            time: "June 13, 2016",
            title: "Hello, WWDC16.",
            detail: "Get a first look at iOS 10, with new features for Messages, Maps, and more. Learn about macOS Sierra, the updated tvOS, and what’s next for watchOS and Apple Pay.",
            thumbnail: "wwdc16_6_13"),
        AppleEvent(
            mainColor: .black,
            backgroundColor: [.white],
            titleColorSet: [.black],
            time: "June 8, 2015",
            title: "WWDC15.",
            detail: "See the announcement of Apple Music, get a preview of OS X El Capitan and iOS 9, and learn what’s next for Apple Watch and developers.",
            thumbnail: "wwdc15_6_8"),
        AppleEvent(
            mainColor: .black,
            backgroundColor: [.white],
            titleColorSet: [.black],
            time: "June 4, 2014",
            title: "WWDC14.",
            detail: "Get a first look at iOS 10, with new features for Messages, Maps, and more. Learn about macOS Sierra, the updated tvOS, and what’s next for watchOS and Apple Pay.",
            thumbnail: "wwdc14_6_4"),
        AppleEvent(
            mainColor: .black,
            backgroundColor: [.white],
            titleColorSet: [.black],
            time: "June 10, 2013",
            title: "WWDC13.",
            detail: "Get an in-depth look at what’s next in iOS and OS X, and learn how to take your apps to the next level. With over 100 sessions, extensive hands–on labs, and engaging events, you’ll connect with Apple engineers and fellow developers for an incredible week of inspiration.",
            thumbnail: "wwdc13_6_10"),
        // ADA
        AppleEvent(
            time: "June, 2023",
            title: "Apple Design Award 2023.",
            detail: "Apple Design Award 2023.",
            thumbnail: "ADA23",
            sectionTitle: ["Inclusivity Winners", "Delight and Fun Winners",
                           "Interaction Winners", "Social Impact Winners",
                           "Visuals and Graphics Winners", "Innovation Winners"],
            bigAttachmentIndex: [0, 0, 0, 0, 0, 0, 0],
    //        bigAttachmentList: ["WyldeFlowers", "Procreate",
    //                            "Overboard!", "Habits",
    //                            "AMusicStory", "Slopes",
    //                            "Gibbon", "RebelGirls",
    //                            "HalideMarkII", "LEGO",
    //                            "MarvelFutureRevolution", "Odio"],
    //        bigAttachmentTitle: ["Wylde Flowers", "Procreate",
    //                             "Overboard!", "(Not Boring) Habits",
    //                             "A Music Story", "Slopes",
    //                             "Gibbon: Beyond the Trees", "RebelGirls",
    //                             "Halide Mark II", "LEGO® Star Wars™: Castaways",
    //                             "Marvel Future Revolution", "Odio"],
            smallSectionTitle: ["Inclusivity Candidates", "Delight and Fun Candidates",
                               "Interaction Candidates", "Social Impact Candidates",
                               "Visuals and Graphics Candidates", "Innovation Candidates"],
            smallAttachmentIndex: [0, 6, 12, 18, 24, 30, 36],
            smallAttachmentList: ["Anne", "Universe",
                                  "PassengerAssistance", "stitch.",
                                  "AncientBoardGameCollection", "FindingHannah",
                                  "Duolingo", "CREME",
                                  "Chantlings", "PocketCardJockeyRideOn!",
                                  "Knotwords", "Afterplace",
                                  "SufflesbyPinterest", "TideGuideCharts&Tables",
                                  "Flighty", "Automatoys",
                                  "Railbound", "KimonoCats",
                                  "Duolingo", "SagoMiniFirstWord",
                                  "Headspace", "Hindsight",
                                  "Endling", "Beecarbonize",
                                  "AnyDistance", "GentlerStreakHealthFitness",
                                  "Riveo", "DiabloImmortal",
                                  "ResidentEvilVillage", "Endling",
                                  "SwingVision", "CamoStudio",
                                  "Rise:Energy&SleepTracker", "ResidentEvilVillage",
                                  "stitch.", "MARVELSNAP"],
            smallAttachmentTitle: ["Anne", "Universe - Website Builder",
                                   "Passenger Assistance", "stitch.",
                                   "Ancient Board Game Collection", "Finding Hannah",
                                   "Duolingo", "CREME",
                                   "Chantlings", "Pocket Card Jockey: Ride On!",
                                   "Knotwords", "Afterplace",
                                   "Suffles by Pinterest", "Tide Guide: Charts & Tables",
                                   "Flighty", "Automatoys",
                                   "Railbound", "Kimono Cats",
                                   "Duolingo", "Sago Mini First Words",
                                   "Headspace", "Hindsight",
                                   "Endling", "Beecarbonize",
                                   "Any Distance", "Gentler Streak Health Fitness",
                                   "Riveo", "Diablo Immortal",
                                   "Resident Evil Village", "Endling",
                                   "SwingVision: A.I. Tennis App", "Camo Studio",
                                   "Rise: Energy & Sleep Tracker", "Resident Evil Village",
                                   "stitch.", "MARVEL SNAP"]
        ),
        AppleEvent(
            time: "June, 2022",
            title: "Apple Design Award 2022.",
            detail: "Apple Design Award 2022.",
            thumbnail: "ADA22",
            sectionTitle: ["Inclusivity Winners", "Delight and Fun Winners",
                           "Interaction Winners", "Social Impact Winners",
                           "Visuals and Graphics Winners", "Innovation Winners"],
            bigAttachmentIndex: [0, 2, 4, 6, 8, 10, 12],
            bigAttachmentList: ["WyldeFlowers", "Procreate",
                                "Overboard!", "Habits",
                                "AMusicStory", "Slopes",
                                "Gibbon", "RebelGirls",
                                "HalideMarkII", "LEGO",
                                "MarvelFutureRevolution", "Odio"],
            bigAttachmentTitle: ["Wylde Flowers", "Procreate",
                                 "Overboard!", "(Not Boring) Habits",
                                 "A Music Story", "Slopes",
                                 "Gibbon: Beyond the Trees", "RebelGirls",
                                 "Halide Mark II", "LEGO® Star Wars™: Castaways",
                                 "Marvel Future Revolution", "Odio"],
            bigAttachmentID: [1458605549, 425073498,
                              1557505849, 1593891243,
                              1584362594, 643351983,
                              1482634476, 1555126110,
                              885697368, 1474344996,
                              1453366542, 1556016869],
            smallSectionTitle: ["Inclusivity Candidates", "Delight and Fun Candidates",
                               "Interaction Candidates", "Social Impact Candidates",
                               "Visuals and Graphics Candidates", "Innovation Candidates"],
            smallAttachmentIndex: [0, 4, 8, 12, 16, 20, 24],
            smallAttachmentList: ["LetterRooms", "Noted.", "Navi", "tint.",
                                  "Chineasy", "Moncage", "PleaseTouchTheArtWork", "Waterllama",
                                  "Gibbon", "Transit", "Vectornator", "WhatRemainsOf",
                                  "ActiveArcade", "Empathy", "HeadSpace", "WyldeFlowers",
                                  "AlienIsolation", "BehindTheFrame", "MDClock", "Habits",
                                  "ActiveArcade", "FocusNoodles", "Procreate", "Townscaper"],
            smallAttachmentTitle: ["Letter Rooms", "Noted.", "Navi", "tint.",
                                   "Chineasy", "Moncage", "Please, Touch The Artwork", "Waterllama",
                                  "Gibbon: Beyond the Trees", "Transit", "Vectornator", "What Remains Of Eidth Finch",
                                  "Active Arcade", "Empathy", "HeadSpace", "WyldeFlowers",
                                  "Alien Isolation", "Behind The Frame", "MD Clock", "(Not Boring) Habits",
                                  "Active Arcade", "Focus Noodles", "Procreate", "Townscaper"]
        ),
        AppleEvent(
            backgroundColor: [Color(red: 11/255, green: 9/255, blue: 12/255)],
            time: "June, 2021",
            title: "Apple Design Award 2021.",
            detail: "Apple Design Award 2021.",
            thumbnail: "ADA21",
            sectionTitle: ["Inclusivity Winners", "Delight and Fun Winners",
                           "Interaction Winners", "Social Impact Winners",
                           "Visuals and Graphics Winners", "Innovation Winners"],
            bigAttachmentIndex: [0, 2, 4, 6, 8, 10, 12],
            bigAttachmentList: ["HoloVista", "VoiceDream",
                                "LittleOrpheus", "PokPokPlayroom",
                                "BirdAlone", "CARROT",
                                "Alba", "BeMyEyes",
                                "Genshin", "Loona",
                                "LOL", "NaadSadhana"],
            bigAttachmentTitle: ["HoloVista", "Voice Dream Reader",
                                 "Little Orpheus", "Pok Pok Playroom",
                                 "Bird Alone", "CARROT Weather",
                                 "Alba: A Wildlife Adventure", "Be My Eyes",
                                 "Genshin Impact", "Loóna",
                                 "League of Legends: Wild Rift", "NaadSadhana"],
            smallSectionTitle: ["Inclusivity Candidates", "Delight and Fun Candidates",
                               "Interaction Candidates", "Social Impact Candidates",
                               "Visuals and Graphics Candidates", "Innovation Candidates"],
            smallAttachmentIndex: [0, 4, 8, 12, 16, 20, 24],
            smallAttachmentList: ["1Password", "AMonster'sExpendition", "Alba", "Me",
                                  "PoolsuiteFM", "RakugakiAR", "Wonderbox", "SouthOfTheCircle",
                                  "Craft", "Nova", "Sp!ng", "Wonderbox",
                                  "Brief", "IfFound", "Klima", "Attentat1942",
                                  "BeyondASteelSky", "MissionToMarsAR", "(NotBoring)Weather", "LittleOrpheus",
                                  "BirdAlone", "BlindDrive", "MuseumAlive", "Universe"],
            smallAttachmentTitle: ["1Password", "A Monster's Expendition", "Alba: A Wildlife Adventure", "Me: A Kid's Diary by Tinybop",
                                   "Poolsuite FM", "RakugakiAR", "Wonderbox", "South of the Circle",
                                   "Craft", "Nova", "Sp!ng", "Wonderbox",
                                  "Brief", "If Found...", "Klima", "Attentat1942",
                                  "Beyond a Steel Sky", "Mission To MarsAR", "(NotBoring) Weather", "Little Orpheus",
                                  "Bird Alone", "Blind Drive", "Museum Alive", "Universe"]
        ),
        AppleEvent(
            time: "June, 2020",
            title: "Apple Design Award 2020.",
            detail: "Apple Design Award 2020.",
            thumbnail: "ADA20",
            sectionTitle: ["Winners"],
            bigAttachmentIndex: [0, 8],
            bigAttachmentList: ["Shapr3D", "Looom","StaffPad","Darkroom",
                                "SayonaraWildHearts", "SongOfBloom",
                                "WhereCardsFall", "Sky"],
            bigAttachmentTitle: ["Shapr 3D", "Looom","StaffPad","Darkroom",
                                 "Sayonara Wild Hearts", "Song Of Bloom",
                                 "Where Cards Fall", "Sky: Children of the Light"]
        ),
        AppleEvent(
            backgroundColor: [Color(red: 18/255, green: 28/255, blue: 58/255)],
            time: "June, 2019",
            title: "Apple Design Award 2019.",
            detail: "Apple Design Award 2019.",
            thumbnail: "ADA19",
            sectionTitle: ["Winners"],
            bigAttachmentIndex: [0, 9],
            bigAttachmentList: ["Ordia", "FlowByMoleskine","TheGardensBetween","Asphalt9",
                                "PixelmatorPhoto", "ELOH",
                                "Butterfly", "Thumper", "HomeCourt"],
            bigAttachmentTitle: ["Ordia", "Flow by Moleskine","The Gardens Between","Asphalt 9: Legends",
                                 "Pixelmator Photo", "ELOH",
                                 "Butterfly iQ — Ultrasound", "Thumper: Pocket Edition", "HomeCourt - The Basketball App"]
        ),
        AppleEvent(
            mainColor: .black,
            backgroundColor: [Color(red: 233/255, green: 234/255, blue: 233/255)],
            titleColorSet: [.black],
            time: "June, 2018",
            title: "Apple Design Award 2018.",
            detail: "Apple Design Award 2018.",
            thumbnail: "ADA18",
            sectionTitle: ["Winners"],
            bigAttachmentIndex: [0, 10],
            bigAttachmentList: ["Agenda", "BANDIMAL","Calzy","iTranslate",
                                "TritonSponge", "Florence",
                                "Playdead’sINSIDE", "Alto’sOdyssey", "Frost",
                                "Oddmar"],
            bigAttachmentTitle: ["Agenda - A new take on notes", "BANDIMAL",
                                 "Calzy","iTranslate Converse",
                                 "Triton Sponge", "Florence",
                                 "Playdead’s INSIDE", "Alto’s Odyssey", "Frost", "Oddmar"]
        ),
        AppleEvent(
            backgroundColor: [Color(red: 18/255, green: 19/255, blue: 16/255)],
            titleColorSet: [.white],
            time: "June, 2017",
            title: "Apple Design Award 2017.",
            detail: "Apple Design Award 2017.",
            thumbnail: "ADA17",
            sectionTitle: ["Winners"],
            bigAttachmentIndex: [0, 12],
            bigAttachmentList: ["Blackbox", "SplitterCritters",
                                "Mushroom11","OldMan'sJourney",
                                "Severed", "Lake",
                                "Bear", "KitchenStories",
                                "Things3", "Elk",
                                "Enlight", "AirMail3"],
            bigAttachmentTitle: ["Blackbox", "Splitter Critters",
                                 "Mushroom11","Old Man's Journey",
                                 "Severed", "Lake",
                                 "Bear", "Kitchen Stories", "Things3",
                                 "Elk", "Enlight", "AirMail 3"]),
    ]

}
